name: evw_client
description: "EVW Flutter Windows Compatibility Probe"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.8.1 <3.9.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^2.4.7
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
